name = "HMDVisualize"
uuid = "cad455f9-137e-4525-af62-4811fc48f070"
authors = ["Atsushi Yoshida <atsushi.yoshida.github@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
